# -*- coding: utf-8 -*-
"""GovernancePolicy — builtin_rules + user_rules two-layer policy engine.

- builtin_rules + user_rules two layers:
    builtin_rules — system built-in protection (resource ask /
        command deny), not modifiable by agent
    user_rules    — generated by user/approve, can be added or removed
- Evaluation flow: ToolRegistry type check → builtin_rules →
    user_rules → global fallback
- Rule generalization: smart generalization on approve (first token +
    *), high-risk commands stay exact
"""

from __future__ import annotations
import copy
import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from fnmatch import fnmatch
from pathlib import Path
from typing import Any, List, Optional

import yaml

from .tool_registry import ToolRegistry, DEFAULT_REGISTRY
from ..sandbox import SandboxConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------


class GovernanceAction(str, Enum):
    ALLOW = "allow"
    DENY = "deny"
    ASK = "ask"
    # bash tool with no hit → sandbox fallback
    SANDBOX_FALLBACK = "sandbox_fallback"


@dataclass
class GovernanceDecision:
    action: GovernanceAction
    reason: str
    sandbox_config: SandboxConfig | None = None
    findings: list[Any] | None = None  # GuardFinding list for approval card
    # Origin of the decision, surfaced as the "Source" line on the approval
    # card. Values: "builtin-rules", "user-rules", or a tool-guard threat
    # category string (e.g. "command_injection", "sensitive_file_access")
    # when the decision was driven by a deep-scan finding.
    source: str = "builtin-rules"


class ToolCallSpec:
    """Specification of a tool call (used by the governor for evaluation).

    Attributes:
        tool_name: Tool name, e.g. "Read", "Bash", "Write"
        target: Tool's target argument, e.g. "src/main.py", "git push"
        agent_id: Agent ID that initiated the call
        session_id: Current session ID
        raw_params: Raw tool call arguments dict
    """

    def __init__(
        self,
        tool_name: str,
        target: str,
        agent_id: str,
        session_id: str,
        raw_params: dict[str, Any] | None = None,
    ) -> None:
        self.tool_name = tool_name
        self.target = target
        self.agent_id = agent_id
        self.session_id = session_id
        self.raw_params = raw_params or {}


@dataclass
class GovernanceRule:
    """Unified policy rule.

    match format: "ToolName(pattern)"
        - ToolName: Read, Write, Bash, Browser, etc.; "*" matches all tools
        - pattern: glob pattern matched against the tool's target argument

    Examples:
        GovernanceRule(match="Bash(git *)", action=GovernanceAction.ALLOW)
        GovernanceRule(match="Write(.env*)", action=GovernanceAction.DENY)
        GovernanceRule(
            match="*(.ssh/**)", action=GovernanceAction.ASK
        )  # all tools
        GovernanceRule(match="Read(src/**)", action=GovernanceAction.ALLOW,
                   grantee="agent-abc", duration="session")

    Action semantics vary by tool type:
        Explicit-resource tools:
            allow → execute directly (no sandbox)
            deny  → reject
            ask   → ask user, execute directly after approval
        Bash-type tools:
            allow → execute in sandbox (pre-authorized, no violation expected)
            deny  → reject (no sandbox)
            ask   → ask user, execute in sandbox after approval
    """

    match: str  # "ToolName(pattern)"
    action: GovernanceAction = GovernanceAction.DENY
    reason: str = ""  # Rule description
    grantee: str = "*"  # Authorized subject
    duration: str = "permanent"  # "session" | "permanent"
    session_id: Optional[str] = None  # Chat session ID

    def _globmatch(self, pattern: str, target: str) -> bool:
        """wcmatch globmatch with directory self-match support."""
        from wcmatch import glob

        flags = glob.GLOBSTAR | glob.BRACE | glob.NEGATE | glob.SPLIT
        if glob.globmatch(target, pattern, flags=flags):
            return True
        if pattern.endswith("/**"):
            dir_pattern = pattern[:-3]
            if glob.globmatch(target, dir_pattern, flags=flags):
                return True
        return False

    def matches_tool_call(
        self,
        tc_spec: ToolCallSpec,
        tool_type: str = "",
    ) -> bool:
        """Determine whether this rule matches the given tool call.

        Matching logic:
            1. grantee match ("*" matches all)
            2. session-level rule: session_id must match
            3. Parse self.match into (rule_tool, rule_pattern)
            4. If rule_tool is "*" it matches all tools
            5. Glob match target against rule_pattern
               - For "*" rules + shell tool, additional substring matching
                 (command may contain sensitive file paths, e.g. "cat .env")

        Note: caller is responsible for resolving target to absolute path
              (WORKSPACE_DIR replacement is done at load time).
        """
        # grantee check
        if self.grantee not in ("*", tc_spec.agent_id):
            return False
        # session-level rule: bound to a specific chat session.
        # Fail-closed: if the rule is session-scoped, the request MUST carry
        # the same session_id. A missing tc_spec.session_id means we cannot
        # prove the request belongs to the bound session, so we refuse to
        # match (do NOT silently fall through, which would let any unscoped
        # request match a session rule).
        if self.duration == "session" and self.session_id:
            if not tc_spec.session_id or self.session_id != tc_spec.session_id:
                return False
        # parse "ToolName(pattern)"
        rule_tool, rule_pattern = _parse_match(self.match)
        # "*" matches all tools (used for builtin resource protection)
        if rule_tool not in ("*", tc_spec.tool_name):
            return False
        is_wildcard = rule_tool == "*"

        use_globmatch = is_wildcard or tool_type == "file"

        if use_globmatch:
            return self._globmatch(rule_pattern, tc_spec.target)
        else:
            return fnmatch(tc_spec.target, rule_pattern)


# ---------------------------------------------------------------------------
# builtin_rules
# ---------------------------------------------------------------------------

DEFAULT_BUILTIN_RULES: List[GovernanceRule] = [
    # ── Resource protection (any tool access requires user confirmation) ──
    GovernanceRule(
        match="*(**/.env*)",
        action=GovernanceAction.ASK,
        reason="Env file may contain secrets/credentials",
    ),
    GovernanceRule(
        match="*(**/.ssh/**)",
        action=GovernanceAction.ASK,
        reason="SSH credentials directory",
    ),
    GovernanceRule(
        match="*(**/*.pem)",
        action=GovernanceAction.ASK,
        reason="Private key file",
    ),
    GovernanceRule(
        match="*(**/*.key)",
        action=GovernanceAction.ASK,
        reason="Private key file",
    ),
    GovernanceRule(
        match="*(**/*.p12)",
        action=GovernanceAction.ASK,
        reason="PKCS#12 certificate bundle",
    ),
    GovernanceRule(
        match="*(**/*.pfx)",
        action=GovernanceAction.ASK,
        reason="PKCS#12 certificate bundle",
    ),
    GovernanceRule(
        match="*(**/.aws/**)",
        action=GovernanceAction.ASK,
        reason="AWS credentials directory",
    ),
    GovernanceRule(
        match="*(**/.gnupg/**)",
        action=GovernanceAction.ASK,
        reason="GPG keys directory",
    ),
    GovernanceRule(
        match="*(**/.kube/**)",
        action=GovernanceAction.ASK,
        reason="Kubernetes config directory",
    ),
    GovernanceRule(
        match="*(**/.netrc)",
        action=GovernanceAction.ASK,
        reason="Netrc login credentials file",
    ),
    GovernanceRule(
        match="*(**/.npmrc)",
        action=GovernanceAction.ASK,
        reason="npm auth token file",
    ),
    GovernanceRule(
        match="*(**/.pypirc)",
        action=GovernanceAction.ASK,
        reason="PyPI API token file",
    ),
    # ── High-risk commands (hard wall, never allowed) ──
    # NOTE: These glob patterns are best-effort fast-path checks.
    # The authoritative shell danger detection is in
    # ``_check_shell_danger_keywords()`` below, which uses regex to
    # catch command variants that fnmatch cannot match.
    GovernanceRule(
        match="Bash(rm * -rf *//*)",
        action=GovernanceAction.DENY,
        reason="Root filesystem deletion",
    ),
    GovernanceRule(
        match="Bash(sudo *)",
        action=GovernanceAction.DENY,
        reason="Privilege escalation prohibited",
    ),
]


# ---------------------------------------------------------------------------
# Shell danger keyword patterns (supplement to glob-based deny rules)
# ---------------------------------------------------------------------------

_SHELL_DANGER_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    # rm with recursive flag targeting root-ish paths (/, /*, /etc, ...)
    # Catches: rm -rf /, rm -r -f /*, rm    -rf  /, rm / -rf, etc.
    (
        re.compile(
            r"\brm\b(?=[^;|&]*\s+-[a-zA-Z]*[rR])[^;|&]*\s+/(?:\s|$|\*)",
        ),
        "Recursive deletion targeting root filesystem",
    ),
    # sudo in any position: start of command, after pipe/semicolon,
    # subshell, absolute path, env prefix, xargs, etc.
    (
        re.compile(
            r"(?:^|[;&|`]|\$\()\s*(?:/usr/s?bin/|/bin/)?sudo\b"
            r"|\bxargs\s+.*\bsudo\b"
            r"|\bcommand\s+sudo\b"
            r"|\benv\s+.*\bsudo\b",
        ),
        "Privilege escalation (sudo)",
    ),
    # Fork bomb patterns
    (
        re.compile(
            r":\(\)\s*\{\s*:\|:\s*&\s*\}",
        ),
        "Fork bomb",
    ),
    # Direct disk write
    (
        re.compile(
            r">\s*/dev/[sh]d[a-z]|\bdd\b[^;|&]*\bof\s*=\s*/dev/",
        ),
        "Direct disk device write",
    ),
    # mkfs (filesystem formatting)
    (
        re.compile(
            r"\bmkfs\b",
        ),
        "Filesystem formatting",
    ),
]


def _check_shell_danger_keywords(command: str) -> Optional[str]:
    """Check a shell command for dangerous patterns via regex.

    Returns the deny reason if a danger pattern matches, else ``None``.
    This supplements the glob-based builtin deny rules to catch command
    variants that ``fnmatch`` cannot match (e.g. flag reordering,
    extra whitespace, absolute path to sudo, piped sudo, etc.).
    """
    # Normalize whitespace for more reliable matching
    normalized = " ".join(command.split())
    for pattern, reason in _SHELL_DANGER_PATTERNS:
        if pattern.search(normalized):
            return reason
    return None


# ---------------------------------------------------------------------------
# Default sandbox deny_paths — paths forbidden for sandbox processes
# ---------------------------------------------------------------------------

DEFAULT_ENV_BLACKLIST: List[str] = [
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_ACCESS_KEY_ID",
]


DEFAULT_SANDBOX_DENY_PATHS: List[str] = [
    # SSH keys and config
    "~/.ssh",
    # AWS credentials
    "~/.aws",
    # GPG keys
    "~/.gnupg",
    # Kubernetes config
    "~/.kube",
    # Google Cloud credentials
    "~/.config/gcloud",
    # Azure CLI credentials
    "~/.azure",
    # Docker auth config
    "~/.docker/config.json",
    # Generic env files (may contain secrets)
    "~/.env",
    # Claude Code config & memory
    "~/.claude",
    # macOS Keychain database
    "~/Library/Keychains",
    # Browser credentials
    "~/Library/Application Support/Google/Chrome/Default/Login Data",
    "~/Library/Application Support/Firefox/Profiles",
    # Git credentials
    "~/.git-credentials",
    "~/.gitconfig",  # may contain tokens in URL
    # Terraform state (may contain sensitive outputs)
    "~/.terraformrc",
    # HashiCorp Vault token
    "~/.vault-token",
    # npm / yarn auth tokens
    "~/.npmrc",
    "~/.yarnrc",
    # pip / PyPI API tokens
    "~/.pypirc",
    # Other common sensitive configs
    "~/.config/gh",  # GitHub CLI
    "~/.config/nix",  # Nix config
    "~/.netrc",  # generic login credentials
]

FILE_READ_TOOLS: frozenset[str] = frozenset(
    {"Read", "ViewImage", "ViewVideo", "SendFileToUser"},
)
FILE_WRITE_TOOLS: frozenset[str] = frozenset({"Write", "Edit", "Append"})


# ---------------------------------------------------------------------------
# Default user_rules (for cold start)
# ---------------------------------------------------------------------------

DEFAULT_USER_RULES: List[GovernanceRule] = [
    # ── Internal tools (no side effects, always allowed) ──
    GovernanceRule(
        match="GetCurrentTime(*)",
        action=GovernanceAction.ALLOW,
        reason="Read-only system tool",
    ),
    GovernanceRule(
        match="GetTokenUsage(*)",
        action=GovernanceAction.ALLOW,
        reason="Read-only usage query",
    ),
    GovernanceRule(
        match="ListAgents(*)",
        action=GovernanceAction.ALLOW,
        reason="Read-only agent list",
    ),
    GovernanceRule(
        match="ChatWithAgent(*)",
        action=GovernanceAction.ALLOW,
        reason="Inter-agent messaging",
    ),
    GovernanceRule(
        match="SubmitToAgent(*)",
        action=GovernanceAction.ALLOW,
        reason="Inter-agent task submission",
    ),
    GovernanceRule(
        match="CheckAgentTask(*)",
        action=GovernanceAction.ALLOW,
        reason="Read-only task status query",
    ),
    GovernanceRule(
        match="DelegateExternalAgent(*)",
        action=GovernanceAction.ALLOW,
        reason="Inter-agent delegation",
    ),
    # ── File tools (operations within WORKSPACE_DIR, always allowed) ──
    GovernanceRule(
        match="Read(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File read within workspace",
    ),
    GovernanceRule(
        match="Write(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File write within workspace",
    ),
    GovernanceRule(
        match="Edit(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File edit within workspace",
    ),
    GovernanceRule(
        match="Append(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File append within workspace",
    ),
    GovernanceRule(
        match="Grep(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="Content search within workspace",
    ),
    GovernanceRule(
        match="Glob(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File listing within workspace",
    ),
    GovernanceRule(
        match="ViewImage(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="Image view within workspace",
    ),
    GovernanceRule(
        match="ViewVideo(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="Video view within workspace",
    ),
    GovernanceRule(
        match="SendFileToUser(WORKSPACE_DIR/**)",
        action=GovernanceAction.ALLOW,
        reason="File send within workspace",
    ),
    # ── Browser (treat as always allowed for now) ──
    GovernanceRule(
        match="Browser(**)",
        action=GovernanceAction.ALLOW,
        reason="Allow all browser access",
    ),
    # ── /tmp ──
    # Allow all tool access under /tmp without prompting.
    GovernanceRule(
        match="*(/tmp/**)",
        action=GovernanceAction.ALLOW,
        reason="Scratch directory access for tmp",
    ),
]


# ---------------------------------------------------------------------------
# GovernancePolicy
# ---------------------------------------------------------------------------


@dataclass
class DetectionRuleConfig:
    """A single pattern-based detection rule (loaded from policy.yaml)."""

    id: str
    tools: List[str] = field(default_factory=list)
    params: List[str] = field(default_factory=list)
    category: str = "command_injection"
    severity: str = "HIGH"
    patterns: List[str] = field(default_factory=list)
    exclude_patterns: List[str] = field(default_factory=list)
    description: str = ""
    remediation: str = ""


@dataclass
class GovernancePolicy:
    """Policy: builtin_rules + user_rules two layers, first-match-wins.

    Loaded from policy_dir/policy.yaml, held by ResourceGovernor.

    Evaluation flow (v2.0):
        Phase 1: Deep security scan (findings accumulation)
        Phase 2: builtin_rules + user_rules first-match-wins
        Phase 3: Fallback + execution_level threshold

    Lifecycle:
        load → evaluate (hot path) → add_rule (user approve) → save
    """

    version: str = "2.0"
    builtin_rules: List[GovernanceRule] = field(default_factory=list)
    user_rules: List[GovernanceRule] = field(default_factory=list)
    env_blacklist: List[str] = field(default_factory=list)
    audit_level: str = "all"  # "all" | "write_only" | "none"

    # v2.0 fields
    execution_level: str = "smart"  # "off" | "auto" | "smart" | "strict"
    sensitive_paths: List[str] = field(default_factory=list)
    shell_evasion_checks: dict[str, bool] = field(default_factory=dict)
    detection_rules: List[DetectionRuleConfig] = field(default_factory=list)

    # Internal reference to registry (defaults to module-level
    # DEFAULT_REGISTRY)
    _registry: ToolRegistry = field(
        default=None,
        repr=False,
        compare=False,
    )

    def __post_init__(self) -> None:
        if self._registry is None:
            self._registry = DEFAULT_REGISTRY

    # ------------------------------------------------------------------
    # Read-only view
    # ------------------------------------------------------------------

    @property
    def rules(self) -> List[GovernanceRule]:
        """Merge builtin_rules + user_rules (read-only snapshot).

        Note: returns a snapshot; modifications will not affect the
        original list.
        Use add_rule() to add new rules.
        """
        return list(self.builtin_rules) + list(self.user_rules)

    def evaluate(  # pylint: disable=too-many-return-statements
        self,
        tc_spec: ToolCallSpec,
    ) -> GovernanceDecision:
        """Evaluate policy decision for a tool call.

        Three-phase evaluation (v2.0):
            Phase 0: Type check — unknown → DENY, internal → ALLOW
            Phase 1: Deep security scan (accumulates findings)
                     CRITICAL findings → immediate DENY
            Phase 2: Policy rules first-match-wins
                     (builtin_rules + user_rules)
            Phase 3: Fallback + execution_level threshold
                     shell → SANDBOX_FALLBACK, others → ASK

        Returns: GovernanceDecision (with optional findings attached)
        """
        # ── Phase 0: ToolRegistry type check ──
        tool_type = self._registry.get_type(tc_spec.tool_name)
        if tool_type == "unknown":
            return GovernanceDecision(
                action=GovernanceAction.DENY,
                reason=f"Unregistered tool: {tc_spec.tool_name}",
            )
        if tool_type == "internal":
            return GovernanceDecision(action=GovernanceAction.ALLOW, reason="")

        # execution_level == OFF → skip Phase 1, go to Phase 2
        skip_deep_scan = self.execution_level == "off"

        # ── Phase 1: Deep security scan ──
        findings: list[Any] = []
        if not skip_deep_scan:
            findings = self._deep_security_scan(tc_spec, tool_type)
            # CRITICAL findings → immediate DENY
            if any(getattr(f, "severity", "") == "CRITICAL" for f in findings):
                reasons = [
                    getattr(f, "title", "")
                    for f in findings
                    if getattr(f, "severity", "") == "CRITICAL"
                ]
                return GovernanceDecision(
                    action=GovernanceAction.DENY,
                    reason="Critical security finding: " + "; ".join(reasons),
                    findings=findings,
                    source=_findings_source(findings),
                )

        # ── Phase 1.5: Shell danger keyword detection ──
        # Regex-based check that catches command variants missed by
        # the fnmatch-based builtin deny rules.
        if tool_type == "shell" and tc_spec.target:
            danger_reason = _check_shell_danger_keywords(tc_spec.target)
            if danger_reason:
                return GovernanceDecision(
                    action=GovernanceAction.DENY,
                    reason=danger_reason,
                    findings=findings,
                )

        # ── Phase 2: builtin_rules + user_rules (first-match-wins) ──
        for rule in self.builtin_rules:
            if rule.matches_tool_call(
                tc_spec,
                tool_type=tool_type,
            ):
                return GovernanceDecision(
                    action=GovernanceAction(rule.action.value),
                    reason=rule.reason,
                    findings=findings or None,
                    source="builtin-rules",
                )

        for rule in self.user_rules:
            if rule.matches_tool_call(
                tc_spec,
                tool_type=tool_type,
            ):
                return GovernanceDecision(
                    action=GovernanceAction(rule.action.value),
                    reason=rule.reason,
                    findings=findings or None,
                    source="user-rules",
                )

        # ── Phase 3: Fallback + execution_level threshold ──
        if tool_type == "shell":
            return GovernanceDecision(
                action=GovernanceAction.SANDBOX_FALLBACK,
                reason="sandbox fallback",
                findings=findings or None,
                source="sandbox",
            )
        return self._apply_execution_level_fallback(tc_spec, findings)

    def _deep_security_scan(
        self,
        tc_spec: ToolCallSpec,
        tool_type: str,
    ) -> list[Any]:
        """Run deep security detectors (Phase 1).

        Delegates to governance.detectors module.
        Returns a list of GuardFinding objects.
        """
        try:
            from .detectors import run_deep_scan

            return run_deep_scan(
                tool_name=tc_spec.tool_name,
                target=tc_spec.target,
                tool_type=tool_type,
                sensitive_paths=self.sensitive_paths,
                detection_rules=self.detection_rules,
                shell_evasion_checks=self.shell_evasion_checks,
            )
        except Exception as exc:
            logger.warning(
                "deep_security_scan failed: %s; continuing without",
                exc,
            )
            return []

    def _apply_execution_level_fallback(
        self,
        tc_spec: ToolCallSpec,  # pylint: disable=unused-argument
        findings: list[Any],
    ) -> GovernanceDecision:
        """Apply execution_level threshold to determine final decision.

        - OFF: should not reach here (scan skipped, but rules didn't match)
        - AUTO: ASK for guarded tools, ALLOW for others
        - SMART: LOW/INFO findings → ALLOW; MEDIUM+ → ASK
        - STRICT: any findings → ASK
        """
        level = self.execution_level

        if not findings:
            # No findings and no rule hit
            if level == "strict":
                return GovernanceDecision(
                    action=GovernanceAction.ASK,
                    reason="STRICT mode: all tool calls require approval",
                    source="STRICT mode",
                )
            return GovernanceDecision(
                action=GovernanceAction.ASK,
                reason="No rule hit",
                source="No rule hit",
            )

        # Has findings — decide based on execution_level
        max_sev = _max_severity(findings)

        if level == "strict":
            return GovernanceDecision(
                action=GovernanceAction.ASK,
                reason=f"STRICT mode: findings detected (max={max_sev})",
                findings=findings,
                source=_findings_source(findings),
            )

        if level == "smart":
            if max_sev in ("INFO", "LOW"):
                return GovernanceDecision(
                    action=GovernanceAction.ALLOW,
                    reason=f"SMART mode: auto-allowed ({max_sev})",
                    findings=findings,
                    source=_findings_source(findings),
                )
            return GovernanceDecision(
                action=GovernanceAction.ASK,
                reason=f"SMART mode: {max_sev} finding requires approval",
                findings=findings,
                source=_findings_source(findings),
            )

        # AUTO / OFF fallback
        return GovernanceDecision(
            action=GovernanceAction.ASK,
            reason="No rule hit",
            findings=findings or None,
            source=_findings_source(findings),
        )

    def evaluate_source(self, tc_spec: ToolCallSpec) -> str:
        """Determine which rule source a tool call matches.

        Returns:
            "builtin"  — matched builtin_rules (no rule recorded on approve)
            "user"     — matched user_rules (rule can be recorded on approve)
            "fallback" — no match, global fallback
        """
        tool_type = self._registry.get_type(tc_spec.tool_name)
        for rule in self.builtin_rules:
            if rule.matches_tool_call(
                tc_spec,
                tool_type=tool_type,
            ):
                return "builtin"
        for rule in self.user_rules:
            if rule.matches_tool_call(
                tc_spec,
                tool_type=tool_type,
            ):
                return "user"
        return "fallback"

    # ------------------------------------------------------------------
    # Dynamic mutation (only operates on user_rules)
    # ------------------------------------------------------------------

    def add_rule(self, rule: GovernanceRule) -> None:
        """Prepend a rule to user_rules (called after user approval).

        New rules are inserted at the beginning so they take priority
        (first-match-wins evaluation). This ensures a newly added DENY
        can override an earlier ALLOW (e.g. Browser(**) → ALLOW).

        Deduplication:
            If an existing user_rule has the same ``match`` / ``action`` /
            ``grantee`` / ``duration`` / ``session_id`` tuple, it is
            removed first so the new rule still ends up at the head
            (refreshing its priority) without growing the list. This
            avoids unbounded growth from repeated identical approvals.

        Note: builtin_rules are read-only and cannot be modified via
            this method.

        TODO: enforce a hard cap (e.g. 1024 user rules) and an LRU /
            TTL eviction policy so long-running workspaces do not pay
            an ever-growing linear scan in ``evaluate``. The current
            dedup is a best-effort stop-gap.
        """
        # Drop any prior rule with the same identity so we don't keep
        # accumulating duplicates on repeated approvals.
        self.user_rules = [
            r
            for r in self.user_rules
            if not (
                r.match == rule.match
                and r.action == rule.action
                and r.grantee == rule.grantee
                and r.duration == rule.duration
                and r.session_id == rule.session_id
            )
        ]
        self.user_rules.insert(0, rule)

    def remove_rule(self, index: int) -> None:
        """Remove a rule from user_rules (Console UI / admin operation).

        Note: builtin_rules cannot be deleted via this method.
        """
        if 0 <= index < len(self.user_rules):
            self.user_rules.pop(index)


# ---------------------------------------------------------------------------
# Rule generalization
# ---------------------------------------------------------------------------


def generalize_rule_match(tool_name: str, target: str) -> str:
    """Construct a match string from an approved rule.

    Current strategy: no generalization, always record exact match
    to avoid security risks from wildcards.

    Args:
        tool_name: policy tool name, e.g. "Bash"
        target: tool's target argument value

    Returns:
        match string, e.g. "Bash(git status)"
    """
    return f"{tool_name}({target})"


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _parse_match(match_str: str) -> tuple[str, str]:
    """Parse "ToolName(pattern)" → (tool_name, pattern).

    Uses index to find the first "(", since the tool name never contains "(".
    Uses rindex to find the last ")" to handle cases where pattern
    contains ")".
    Example: "Bash(git *)" → ("Bash", "git *")
             "*(.env*)"   → ("*", ".env*")      # wildcard for all tools
             "Read(src/**)" → ("Read", "src/**")
             "Bash(echo $(date))" → ("Bash", "echo $(date)")
    """
    paren = match_str.index("(")
    close = match_str.rindex(")")
    tool_name = match_str[:paren]
    pattern = match_str[paren + 1 : close]
    return tool_name, pattern


_SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def _max_severity(findings: list[Any]) -> str:
    """Return the highest severity string from a list of findings."""
    if not findings:
        return "SAFE"
    for sev in _SEVERITY_ORDER:
        if any(getattr(f, "severity", "") == sev for f in findings):
            return sev
    return "SAFE"


def _findings_source(findings: list[Any]) -> str:
    """Pick the approval-card ``source`` for a finding-driven decision.

    Returns the threat category of the highest-severity finding (e.g.
    ``"command_injection"``), falling back to ``"builtin-rules"`` when no
    finding carries a category.
    """
    if not findings:
        return "builtin-rules"
    for sev in _SEVERITY_ORDER:
        for f in findings:
            if getattr(f, "severity", "") == sev:
                category = getattr(f, "category", None)
                if category:
                    return (
                        category.value
                        if hasattr(category, "value")
                        else str(category)
                    )
    return "builtin-rules"


# ---------------------------------------------------------------------------
# Load / persist
# ---------------------------------------------------------------------------


def load_governance_policy(
    policy_dir: str,
    workspace_dir: str,
) -> GovernancePolicy:
    """Load from policy_dir/policy.yaml; return default policy if missing.

    Args:
        policy_dir: directory containing policy.yaml
        workspace_dir: used to replace WORKSPACE_DIR placeholders in rules

    Supports both v1.0 and v2.0 YAML formats.
    """
    path = Path(policy_dir) / "policy.yaml"
    if not path.exists():
        return _create_default_policy(workspace_dir)

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except Exception:
        return _create_default_policy(workspace_dir)

    if not isinstance(data, dict):
        return _create_default_policy(workspace_dir)

    version = data.get("version", "1.0")
    audit_level = data.get("audit_level", "all")

    # ── builtin_rules: ALWAYS sourced from code (not from YAML) ──
    # Rationale: builtin_rules encode system-level protections (e.g. ASK on
    # ``.env`` / ``.ssh``). Honoring a YAML override here would let a
    # tampered or accidentally truncated policy file silently weaken those
    # protections. Any ``builtin_rules`` key in YAML is intentionally
    # ignored.
    if "builtin_rules" in data:
        logger.warning(
            "load_governance_policy: ignoring 'builtin_rules' in %s; "
            "builtin rules are managed in code and cannot be overridden "
            "via YAML.",
            path,
        )
    builtin_rules = copy.deepcopy(DEFAULT_BUILTIN_RULES)

    # ── user_rules ──
    user_rules = _parse_rules(data.get("user_rules", []))

    # ── env_blacklist ──
    env_blacklist = data.get("env_blacklist", [])
    if not isinstance(env_blacklist, list):
        env_blacklist = []

    # ── Cold start: fill in missing default rules ──
    if not user_rules:
        user_rules = copy.deepcopy(DEFAULT_USER_RULES)
    if not env_blacklist:
        env_blacklist = list(DEFAULT_ENV_BLACKLIST)

    # ── v2.0 fields ──
    execution_level = data.get("execution_level", "smart")
    if execution_level not in ("off", "auto", "smart", "strict"):
        logger.warning(
            "load_governance_policy: invalid execution_level '%s'; "
            "defaulting to 'smart'.",
            execution_level,
        )
        execution_level = "smart"

    sensitive_paths = data.get("sensitive_paths", [])
    if not isinstance(sensitive_paths, list):
        sensitive_paths = []

    shell_evasion_checks = data.get("shell_evasion_checks", {})
    if not isinstance(shell_evasion_checks, dict):
        shell_evasion_checks = {}

    detection_rules = _parse_detection_rules(
        data.get("detection_rules", []),
    )

    # ── Replace WORKSPACE_DIR with actual path ──
    if workspace_dir:
        _resolve_workspace_dir(builtin_rules, workspace_dir)
        _resolve_workspace_dir(user_rules, workspace_dir)

    return GovernancePolicy(
        version=version,
        builtin_rules=builtin_rules,
        user_rules=user_rules,
        env_blacklist=env_blacklist,
        audit_level=audit_level,
        execution_level=execution_level,
        sensitive_paths=sensitive_paths,
        shell_evasion_checks=shell_evasion_checks,
        detection_rules=detection_rules,
    )


def save_governance_policy(
    policy: GovernancePolicy,
    policy_dir: str,
    workspace_dir: str = "",
) -> None:
    """Write policy.yaml (v2.0 format).

    Args:
        policy: policy to persist
        policy_dir: directory to write policy.yaml
        workspace_dir: workspace path, used to restore actual paths back to
                       WORKSPACE_DIR placeholders (keeps yaml portable)
    """
    builtin_rules = copy.deepcopy(policy.builtin_rules)
    user_rules = copy.deepcopy(policy.user_rules)

    # ── Restore actual paths to WORKSPACE_DIR placeholders ──
    if workspace_dir:
        _unresolve_workspace_dir(builtin_rules, workspace_dir)
        _unresolve_workspace_dir(user_rules, workspace_dir)

    path = Path(policy_dir) / "policy.yaml"
    # NOTE: builtin_rules are NOT written to YAML. They are always loaded
    # from DEFAULT_BUILTIN_RULES in code. This prevents a tampered policy
    # file from weakening system-level protections.
    data: dict[str, Any] = {
        "version": policy.version,
        "execution_level": policy.execution_level,
        "audit_level": policy.audit_level,
        "env_blacklist": list(policy.env_blacklist),
        "user_rules": [_rule_to_dict(r) for r in user_rules],
    }

    # v2.0 fields (only write when non-empty to keep YAML clean)
    if policy.sensitive_paths:
        data["sensitive_paths"] = list(policy.sensitive_paths)
    if policy.shell_evasion_checks:
        data["shell_evasion_checks"] = dict(policy.shell_evasion_checks)
    if policy.detection_rules:
        data["detection_rules"] = [
            _detection_rule_to_dict(r) for r in policy.detection_rules
        ]

    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(
            data,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


# Default shell evasion checks (migrated from config.json)
_DEFAULT_SHELL_EVASION_CHECKS: dict[str, bool] = {
    "command_substitution": True,
    "obfuscated_flags": True,
    "backslash_escaped_whitespace": True,
    "backslash_escaped_operators": True,
    "newlines": True,
    "comment_quote_desync": True,
    "quoted_newline": True,
}

# Default sensitive paths (migrated from config.json)
_DEFAULT_SENSITIVE_PATHS: List[str] = [
    "~/.ssh/",
    "~/.aws/",
    "~/.gnupg/",
    "~/.kube/",
    "~/.config/gcloud/",
    "~/.azure/",
    "~/.docker/config.json",
    "~/.env",
    "~/.git-credentials",
    "~/.netrc",
    "~/.npmrc",
    "~/.pypirc",
]


def _create_default_policy(workspace_dir: str = "") -> GovernancePolicy:
    """Create a policy with full default rules (cold start, v2.0)."""
    builtin_rules = copy.deepcopy(DEFAULT_BUILTIN_RULES)
    user_rules = copy.deepcopy(DEFAULT_USER_RULES)
    if workspace_dir:
        _resolve_workspace_dir(builtin_rules, workspace_dir)
        _resolve_workspace_dir(user_rules, workspace_dir)
    return GovernancePolicy(
        version="2.0",
        builtin_rules=builtin_rules,
        user_rules=user_rules,
        env_blacklist=list(DEFAULT_ENV_BLACKLIST),
        execution_level="smart",
        sensitive_paths=list(_DEFAULT_SENSITIVE_PATHS),
        shell_evasion_checks=dict(_DEFAULT_SHELL_EVASION_CHECKS),
    )


def _resolve_workspace_dir(rules: List[GovernanceRule], workspace_dir: str):
    """Replace WORKSPACE_DIR in rules with actual paths (in-place)."""
    for rule in rules:
        if "WORKSPACE_DIR" in rule.match:
            rule.match = rule.match.replace("WORKSPACE_DIR", workspace_dir)


def _unresolve_workspace_dir(rules: List[GovernanceRule], workspace_dir: str):
    """Restore actual paths in rules back to WORKSPACE_DIR placeholders."""
    for rule in rules:
        if workspace_dir in rule.match:
            rule.match = rule.match.replace(workspace_dir, "WORKSPACE_DIR")


def _parse_rules(
    items: Optional[list[dict[str, Any]]],
) -> List[GovernanceRule]:
    """Parse a list of GovernanceRule from YAML list."""
    if not items:
        return []
    rules = []
    for item in items:
        if not isinstance(item, dict) or "match" not in item:
            continue
        action_str = item.get("action", "deny")
        try:
            action = GovernanceAction(action_str)
        except ValueError:
            action = GovernanceAction.DENY
        rules.append(
            GovernanceRule(
                match=item["match"],
                action=action,
                reason=item.get("reason", ""),
                grantee=item.get("grantee", "*"),
                duration=item.get("duration", "permanent"),
                session_id=item.get("session_id"),
            ),
        )
    return rules


def _rule_to_dict(rule: GovernanceRule) -> dict[str, Any]:
    """Serialize a GovernanceRule to dict (for YAML output)."""
    d = {
        "match": rule.match,
        "action": rule.action.value,
    }
    if rule.reason:
        d["reason"] = rule.reason
    if rule.grantee != "*":
        d["grantee"] = rule.grantee
    if rule.duration != "permanent":
        d["duration"] = rule.duration
    if rule.session_id:
        d["session_id"] = rule.session_id
    return d


def _detection_rule_to_dict(rule: DetectionRuleConfig) -> dict[str, Any]:
    """Serialize a DetectionRuleConfig to dict (for YAML output)."""
    d: dict[str, Any] = {"id": rule.id}
    if rule.tools:
        d["tools"] = rule.tools
    if rule.params:
        d["params"] = rule.params
    if rule.category != "command_injection":
        d["category"] = rule.category
    d["severity"] = rule.severity
    if rule.patterns:
        d["patterns"] = rule.patterns
    if rule.exclude_patterns:
        d["exclude_patterns"] = rule.exclude_patterns
    if rule.description:
        d["description"] = rule.description
    if rule.remediation:
        d["remediation"] = rule.remediation
    return d


def _parse_detection_rules(
    items: list[dict[str, Any]] | None,
) -> List[DetectionRuleConfig]:
    """Parse detection_rules from YAML into DetectionRuleConfig."""
    if not items:
        return []
    rules: List[DetectionRuleConfig] = []
    for item in items:
        if not isinstance(item, dict) or "id" not in item:
            continue
        try:
            rules.append(
                DetectionRuleConfig(
                    id=item["id"],
                    tools=item.get("tools", []),
                    params=item.get("params", []),
                    category=item.get("category", "command_injection"),
                    severity=item.get("severity", "HIGH"),
                    patterns=item.get("patterns", []),
                    exclude_patterns=item.get("exclude_patterns", []),
                    description=item.get("description", ""),
                    remediation=item.get("remediation", ""),
                ),
            )
        except Exception as exc:
            logger.warning(
                "Skipping invalid detection rule '%s': %s",
                item.get("id", "?"),
                exc,
            )
    return rules
