# -*- coding: utf-8 -*-
"""ToolRegistry — Single source of truth for tool metadata.

Each tool declares on registration:
    - Type (file / network / shell / internal)
    - Target parameter name (file_path / command / url …)
    - Python function name → policy tool name mapping

Relationship with policy.yaml:
    ToolRegistry: what a tool is (type, parameter name)
        → static, registered in code
    policy.yaml:  what a tool can do (rules, default perms)
        → dynamic, generated by user/approve
"""

from __future__ import annotations
import os
from typing import Any, Dict, List


class ToolRegistry:
    """Tool metadata registry."""

    def __init__(self) -> None:
        self._types: Dict[str, str] = {}
        self._target_params: Dict[str, str] = {}
        self._python_name_map: Dict[str, str] = {}
        # Tools whose target should combine path + pattern
        # (e.g. Glob: pattern is a file glob, so path+pattern
        # forms a complete filesystem path pattern for rule matching).
        self._pattern_params: Dict[str, str] = {}

    def register(
        self,
        tool_name: str,
        tool_type: str,
        target_param: str,
        pattern_param: str = "",
    ) -> None:
        """Register a tool.

        Args:
            tool_name: policy-layer tool name, e.g. "Read"
            tool_type: "file" | "network" | "shell" | "internal"
            target_param: target parameter name, e.g. "file_path", "command"
            pattern_param: for file-search tools (e.g. Glob), the parameter
                name holding the glob pattern. When set, ``extract_target``
                combines path + pattern into a single filesystem path pattern.
        """
        self._types[tool_name] = tool_type
        self._target_params[tool_name] = target_param
        if pattern_param:
            self._pattern_params[tool_name] = pattern_param

    def register_python_name(self, python_name: str, policy_name: str) -> None:
        """Register a python function name → policy tool name mapping."""
        self._python_name_map[python_name] = policy_name

    def get_type(self, tool_name: str) -> str:
        """Return the tool's type. Returns "unknown" if not registered."""
        return self._types.get(tool_name, "unknown")

    def get_target_param(self, tool_name: str) -> str:
        """Return the tool's target parameter name.

        Returns "" if not registered.
        """
        return self._target_params.get(tool_name, "")

    def python_to_policy_name(self, python_name: str) -> str:
        """Map a python function name to a policy tool name.

        Checks explicit mapping first; if no mapping exists, converts
        snake_case → PascalCase.
        """
        override = self._python_name_map.get(python_name)
        if override:
            return override
        parts = python_name.split("_")
        return "".join(p.capitalize() for p in parts)

    def extract_target(
        self,
        tool_name: str,
        input_data: dict[str, Any],
        workspace_dir: str = "",
    ) -> str:
        """Extract the target from tool call arguments."""
        param = self.get_target_param(tool_name)
        if not param:
            return ""

        # 1) Get base path from input
        path = input_data.get(param, "")
        path = str(path) if path else ""

        # 2) For file tools, resolve empty/relative path using workspace_dir
        if self._types.get(tool_name) == "file" and workspace_dir:
            if not path:
                path = workspace_dir
            elif not os.path.isabs(path):
                path = os.path.join(workspace_dir, path)

        # 3) Append pattern for file-search tools (e.g. Glob)
        pattern_param = self._pattern_params.get(tool_name)
        if pattern_param:
            pattern = input_data.get(pattern_param, "")
            if pattern:
                path = (
                    os.path.join(path, str(pattern)) if path else str(pattern)
                )

        return path

    def get_all_tool_names(self) -> List[str]:
        """Return all registered tool names."""
        return list(self._types.keys())


# ---------------------------------------------------------------------------
# Default registry instance (21 tools)
# ---------------------------------------------------------------------------


def _create_default_registry() -> ToolRegistry:
    """Create and populate the default ToolRegistry."""
    registry = ToolRegistry()

    # ── File tools (12) ──
    registry.register("Read", "file", "file_path")
    registry.register("Write", "file", "file_path")
    registry.register("Edit", "file", "file_path")
    registry.register("Append", "file", "file_path")
    registry.register("Grep", "file", "path")
    registry.register("Glob", "file", "path", pattern_param="pattern")
    registry.register("SendFileToUser", "file", "file_path")
    registry.register("ViewImage", "file", "image_path")
    registry.register("ViewVideo", "file", "video_path")
    registry.register("DesktopScreenshot", "file", "path")
    registry.register("SetUserTimezone", "file", "timezone")

    # ── Network tools (1) ──
    registry.register("Browser", "network", "url")

    # ── Shell tools (1) ──
    registry.register("Bash", "shell", "command")

    # ── Internal tools (7) ──
    registry.register("GetCurrentTime", "internal", "")
    registry.register("GetTokenUsage", "internal", "")
    registry.register("ListAgents", "internal", "")
    registry.register("MaterializeSkill", "internal", "")
    registry.register("ChatWithAgent", "internal", "agent_id")
    registry.register("SubmitToAgent", "internal", "agent_id")
    registry.register("CheckAgentTask", "internal", "task_id")
    registry.register("DelegateExternalAgent", "internal", "runner")
    registry.register("MemorySearch", "internal", "")

    # ── Python function name mappings ──
    registry.register_python_name("execute_shell_command", "Bash")
    registry.register_python_name("read_file", "Read")
    registry.register_python_name("write_file", "Write")
    registry.register_python_name("edit_file", "Edit")
    registry.register_python_name("memory_search", "MemorySearch")
    registry.register_python_name("append_file", "Append")
    registry.register_python_name("grep_search", "Grep")
    registry.register_python_name("glob_search", "Glob")
    registry.register_python_name("browser_use", "Browser")
    registry.register_python_name("desktop_screenshot", "DesktopScreenshot")
    registry.register_python_name("send_file_to_user", "SendFileToUser")
    registry.register_python_name("view_image", "ViewImage")
    registry.register_python_name("view_video", "ViewVideo")
    registry.register_python_name("get_current_time", "GetCurrentTime")
    registry.register_python_name("set_user_timezone", "SetUserTimezone")
    registry.register_python_name("get_token_usage", "GetTokenUsage")
    registry.register_python_name(
        "delegate_external_agent",
        "DelegateExternalAgent",
    )
    registry.register_python_name("list_agents", "ListAgents")
    registry.register_python_name("chat_with_agent", "ChatWithAgent")
    registry.register_python_name("submit_to_agent", "SubmitToAgent")
    registry.register_python_name("check_agent_task", "CheckAgentTask")
    registry.register_python_name("materialize_skill", "MaterializeSkill")

    return registry


DEFAULT_REGISTRY = _create_default_registry()
